<?php 

session_start(); 


if(isset($_SESSION['user']) && $_SESSION['user'] === 'admin') {
    header("Location: secret.php"); 
    exit();
}



?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page d'accueil</title>
</head>
<body>
    <h1>Page d'accueil</h1>
    
    <?php
  
    ?>

    <form method="post" action="index.php">
        <label for="NewUsername">Identifiant :</label>
        <input type="text" id="NewUsername" name="NewUsername" required><br>

        <label for="NewPassword">Mot de passe :</label>
        <input type="password" id="NewPassword" name="NewPassword" required><br>

        <button type="submit">inscription</button>
    </form>

    <form action="connexion.php">
        <button type="submit">j'ai deja un compte</button>
    </form>

</body>
</html>
 
    <?php if(isset($_POST["NewPassword"]) && isset($_POST["NewUsername"])){
    require "sign.php";
}
?>

